run10 : out10
	./out10
compile10 : question.c record.c
	gcc -o out10 question.c record.c

run100 : out100
	./out100	
compile100 : question.c record.c
	gcc -o out100 question.c record.c

run1000 : out1000
	./out1000	
compile1000 : question.c record.c
	gcc -o out1000 question.c record.c

run10000 : out10000
	./out10000	
compile10000 : question.c record.c
	gcc -o out10000 question.c record.c

run100000 : out100000
	./out100000
compile100000 : question.c record.c
	gcc -o out100000 question.c record.c
record.o : record.c
	gcc -c record.c